;KODLAMA SABLONU

	list		p=16f877A	; hangi pic
	#include	<p16f877A.inc>	; SFR register 'lar?n tan?mland??? kutuphane
	
    __CONFIG H'3F31'

; BU UYGULAMADA HER RC2 KESMESINDE (CAPTURE) TMR1 DEGERI EKRANA YAZILIYOR

	
;KULLANILACAK DEGISKENLER


SAYAC	EQU	0X23
SAYAC2		EQU	0X24

DEGER	EQU	0X25
TMP		EQU	0x31	; GECICI ISLER ICIN






;*** Kesme durumunda kaydedilmesi gereken SFR ler icin kullanilacak yardimci degiskenler
w_temp		EQU	0x7D		
status_temp	EQU	0x7E		
pclath_temp	EQU	0x7F					


;********************************
    ORG     0x000             	; Baslama vektoru

    nop			  			  	; ICD ozelliginin aktif edilmesi icin gereken bekleme 
    goto    BASLA              	

	
;********************************
    ORG     0x004             	

    RETFIE


BASLA	
  BANKSEL   TRISB
  CLRF	    TRISB
  BANKSEL   TRISD
  CLRF	    TRISD
  BANKSEL   TRISC
  MOVLW	0XFF
  MOVWF	TRISC
  BANKSEL   PORTB
  CLRF	PORTB
  CLRF	PORTC
  CLRF	PORTD
  BANKSEL   SPBRG
  MOVLW	    B'00011001'
  MOVWF	    SPBRG
  BANKSEL   TXSTA
  MOVLW	    B'00000100'
  MOVWF	    TXSTA
  
  BANKSEL   RCSTA
  MOVLW	B'10010000'
  MOVWF	RCSTA
  
  BSF	PORTB,2
  BCF	PORTB,3
  CALL	LCD_ISLEM
KONTROL
  BTFSC	PIR1,RCIF
  GOTO	TERMINAL_YAZ
  GOTO	KONTROL
TERMINAL_YAZ
  BANKSEL   RCREG
  MOVF	RCREG,W
  CALL	VERI_YAZ
  GOTO	KONTROL
LCD_ISLEM
  MOVLW	0X02
  CALL	KOMUT_YAZ
  MOVLW	0X0C
  CALL	KOMUT_YAZ
  MOVLW	0X28
  CALL	KOMUT_YAZ
  RETURN
KOMUT_YAZ
  MOVWF	DEGER
  SWAPF	DEGER,W
  CALL	LCD_KOMUT_GONDER
  MOVF	DEGER,W
  CALL	LCD_KOMUT_GONDER
  RETURN
LCD_KOMUT_GONDER
  ANDLW	0X0F
  BANKSEL   PORTD
  MOVWF	PORTD
  BANKSEL   PORTB
  BCF	PORTB,4
  BSF	PORTB,6
  CALL	GECIKME
  BCF	PORTB,6
  RETURN
VERI_YAZ
  MOVWF	DEGER
  SWAPF	DEGER,W
  CALL	LCD_VERI_GONDER
  MOVF	DEGER,W
  CALL	LCD_VERI_GONDER
  RETURN
  
LCD_VERI_GONDER
  ANDLW	0X0F
  BANKSEL   PORTD
  MOVWF	PORTD
  BANKSEL   PORTB
  BSF	PORTB,4
  BSF	PORTB,6
  CALL	GECIKME
  BCF	PORTB,6
  RETURN
  
GECIKME
  MOVLW	0X01
  MOVWF	SAYAC
GECIKME1
  DECFSZ    SAYAC,F
  GOTO	GECIKME1
  RETURN
   
END
   
